{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.hpa }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  namespace: {{ $.Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $svc.hpa.minReplicas | default 1 }}
  maxReplicas: {{ $svc.hpa.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.hpa.targetCPUUtilizationPercentage | default 70 }}
{{- end }}
{{- end }}
